[package]
name = "aries-data-generator-toolkit"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "adg"
path = "src/main.rs"

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

