[package]
name = "aries-cloudagent-controller-ferris"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "accf"
path = "src/main.rs"

[dependencies]
clap        = { version = "2.33.3" , features = ["yaml"] }
serde       = { version = "1.0.130", features = ["derive"] }
reqwest     = { version = "0.11"   , features = ["json"] }
tokio       = { version = "1"      , features = ["full"] }
serde_json  = "1.0.68"
qr2term     = "0.2.2"
colored     = "2.0.0"
yaml-rust   = "0.4.5" 
async-trait = "0.1.51"
rust-ini    = "0.17.0"
