[package]
name = "aries-cli"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Animo Solutions"]
description = "A simple Aries Cloudagent Controller"
homepage = "animo.id"
edition = "2018"
repository = "https://github.com/animo/aries-cli"
keywords = ["aries", "cloudagent", "controller", "cli-tool"]
categories = ["aries", "cloudagent", "controller", "cli-tool"]
readme = "README.md"

[[bin]]
name = "acl"
path = "src/main.rs"

[dependencies]
clap        = { version = "2.33.3" , features = ["yaml"] }
serde       = { version = "1.0.130", features = ["derive"] }
reqwest     = { version = "0.11"   , features = ["json"] }
tokio       = { version = "1"      , features = ["full"] }
serde_json  = "1.0.68"
qr2term     = "0.2.2"
colored     = "2.0.0"
yaml-rust   = "0.4.5" 
async-trait = "0.1.51"
rust-ini    = "0.17.0"
clipboard   = "0.5.0"
